dolaposcrumy/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'dolaposcrumy'

urlpatterns = [
    # path('', views.home_page, name='home_page'),
    path('dolaposcrumy/adduser/', views.add_user, name='add_user'),
    # path('dolaposcrumy/addtask/', views.add_task, name='add_task'),
    path('dolaposcrumy/<int:pk>/edit_task/', views.edit_task, name='edit_task'),
    path('dolaposcrumy/accessdenied', views.user_passes_test, name = 'access_denied'),
    path('', views.GoalsListView.as_view(), name='home'),
    path('dolaposcrumy/new',views.GoalCreateView.as_view(), name='new_goal'),
    # path('dolaposcrumy/<int:pk>/edit/', views.GoalsUpdateView.as_view(), name='edit_goal'),
    path('dolaposcrumy/<int:pk>/delete/',views.DeleteGoalView.as_view(), name='delete_goal'),
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dolaposcrumy.urls')),

]

dolaposcrumy/models.py
from django.db import models
import uuid
from django.urls import reverse

# Create your models here.

class ScrumyUser(models.Model):
    userName = models.EmailField(max_length=70, blank=True, null=False)
    firstName = models.CharField(max_length=100, null=False)
    lastName = models.CharField(max_length=100, null=False)


    def __str__(self):
        return self.userName

#New Model
class ScrumyStatus(models.Model):
    STATUS = (
        ('WT', 'Weekly Task'),
        ('DT', 'Daily Task'),
        ('V', 'Verified'),
        ('D', 'Done'),
    )
    status = models.CharField(max_length=50, choices=STATUS)

    def __str__(self):
        return self.status


class ScrumyGoals(models.Model):
    user_id = models.ForeignKey(ScrumyUser, on_delete=models.CASCADE)
    status_id = models.ForeignKey(ScrumyStatus, on_delete=models.CASCADE) #New field
    task = models.TextField()

    def get_absolute_url(self):
        return reverse('dolaposcrumy:home')

    def __str__(self):
        return self.task

dolaposcrumy/forms.py
from django import forms

from .models import ScrumyUser, ScrumyGoals, ScrumyStatus

class AddUser(forms.ModelForm):
    class Meta:
        model = ScrumyUser
        fields = ('userName','firstName','lastName')

# class StatusChoice(forms.ModelForm):
#     class Meta:
#         model = ScrumyStatus
#         fields = ('__all__')

class AddTask(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ('__all__')

class EditTask(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ('__all__')



# class MoveTask(forms.ModelForm):
#
#     class Meta:
#         model = ScrumyUser
#         fields = ('userName')

dolaposcrumy/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import ScrumyGoals, ScrumyUser, ScrumyStatus
from .forms import AddUser, AddTask, EditTask
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User, Group
from django.views.generic import ListView, CreateView, DeleteView

# Create your views here.
class GoalsListView(ListView):
    model = ScrumyGoals
    template_name ='dolaposcrumy/home_page.html'


# def home_page(request):
#     scrumy_goals = ScrumyGoals.objects.all()
#     return render(request, 'dolaposcrumy/home_page.html', {'scrumy_goals':scrumy_goals})


@login_required
def add_user(request):
    if request.method == "POST":
        form = AddUser(request.POST)
        if form.is_valid():
            addUser = form.save(commit=False)
            addUser.save()
            return redirect('/')
    else:
        form = AddUser()
        return render(request, 'dolaposcrumy/add_user.html', {'form': form})


class GoalCreateView(CreateView, LoginRequiredMixin):
    model = ScrumyGoals
    template_name = 'dolaposcrumy/add_task.html'
    fields = '__all__'


# @login_required
# def add_task(request):
#     if request.method == "POST":
#         form = AddTask(request.POST)
#         if form.is_valid():
#             addTask = form.save(commit=False)
#             addTask.save()
#             return redirect('/')
#     else:
#
#         form= AddTask()
#         return render(request, 'dolaposcrumy/add_task.html', {'form': form})

# def home(request):
#
#     a = ScrumyGoals.objects.all().filter(task_category='daily goals')
#     a = get_object_or_404(ScrumyGoals, task_category='daily goals')
#     return render(request, 'registration/login.html', {'a': a })
#
#

# @login_required
# @user_passes_test(lambda u: u.groups.filter(name='Regular').count() == 0, login_url=None, redirect_field_name='/')
# def edit_task(request, pk):
#     addTask = get_object_or_404(ScrumyGoals, pk=pk)
#     if request.method == "POST":
#         form = AddTask(request.POST, instance=addTask)
#         if form.is_valid():
#             addTask = form.save(commit=False)
#             addTask.save()
#             return redirect('/', pk=addTask.pk)
#
#     else:
#         form = AddTask(instance=addTask)
#         return render(request, 'dolaposcrumy/add_task.html', {'form': form})

# class GoalsUpdateView(UpdateView):
#     model = ScrumyGoals
#     template_name = 'dolaposcrumy/edit_task.html'
#     fields = '__all__'

@login_required()
def edit_task(request, pk):
    # addTask = get_object_or_404(ScrumyGoals, pk=pk)
    if request.method == "POST":
        active_user = request.user
        active_user_group = Group.objects.get(user = active_user)
        task = ScrumyGoals.objects.get(pk = pk)
        if request.POST.get("status_id_id") == "WT":
            task.status_id_id = 4
            task.save()
            return redirect("/")

        elif request.POST.get("status_id_id") == "DT":
            task.status_id_id = 5
            task.save()
            return redirect("/")

        elif request.POST.get("status_id_id") == "V":
            Regular = Group.objects.get(pk = 1)
            if active_user_group.pk == Regular.pk:
                return render(request, "dolaposcrumy/denied.html")
            else:
                task.status_id_id = 6
                task.save()
                return redirect("/")

        elif request.POST.get("status_id_id") == "D":
            Regular = Group.objects.get(pk = 1)
            if active_user_group.pk == Regular.pk:
                return render(request, "dolaposcrumy/denied.html")
            else:
                task.status_id_id = 7
                task.save()
                return redirect("/")
    else:
        # form = AddTask(instance=addTask)
        return render(request, 'dolaposcrumy/edit_task.html', )

class DeleteGoalView(DeleteView, LoginRequiredMixin):
    model = ScrumyGoals
    template_name = 'dolaposcrumy/delete_task.html'
    success_url = reverse_lazy('dolaposcrumy:home')

dolaposcrumy/templates/dolaposcrumy/add_status.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}
<h1>New User</h1>
    <form action="" method="post" class="form-control">{% csrf_token %}
      {{ form.as_p }}
        <button type="submit" value="Save" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

dolaposcrumy/templates/dolaposcrumy/add_task.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}

<h1>New Task</h1>
    <form action="" method="post" class="form-control">{% csrf_token %}
      {{ form.as_p }}
        <button type="submit" value="Save" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

dolaposcrumy/templates/dolaposcrumy/add_user.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}
<h1>New User</h1>
    <form action="" method="post" class="form-control">{% csrf_token %}
      {{ form.as_p }}
        <button type="submit" value="Save" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}

dolaposcrumy/templates/dolaposcrumy/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>dolaposcrumy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body style="background-color: #9d9d9d">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand active" href="{% url 'dolaposcrumy:home' %}">Dolapo Scrumy</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <p class="text-info">Hi {{ user.username }}!</p>
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-user"></span> logout</a></li>
             {% else %}
                You are not logged in.
              <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
        <div class="row">

            {% block content %}
            {% endblock %}

        </div>
    </div>


</body>
</html>

dolaposcrumy/templates/dolaposcrumy/delete_task.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}
<h1>Delete Task</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete task {{ scummer.task }} ?</p>
      <input type="submit" value="Confirm" />
    </form>
{% endblock %}

dolaposcrumy/templates/dolaposcrumy/denied.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}

<h1> ACCESS DENIED </h1>

{% endblock%}

dolaposcrumy/templates/dolaposcrumy/edit_task.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}<h1>Edit Task</h1>
    <form action="" method="post" class="form-control">{% csrf_token %}
        <fieldset>
            <legend>Choose Category</legend>
            <select title="Status" name="status_id_id">

                <option value="WT">Weekly Task</option>
                <option value="DT">Daily Task</option>
                <option value="V">Verified</option>
                <option value="D">Done</option>

            </select>
            <input type="submit" value="complete">

        </fieldset>
    </form>
{% endblock %}

dolaposcrumy/templates/dolaposcrumy/home_page.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}

    <table  class="table table-responsive-sm table-bordered">
    <thead class="thead-dark">
        <tr>
          <th scope="col"></th>
          <th scope="col">User</th>
          <th scope="col"></th>
          <th scope="col">Weekly Goals</th>
          <th scope="col">Daily Goals</th>
          <th scope="col">Verify</th>
          <th scope="col">Done</th>

        </tr>
    </thead>
{#{% if scrumy_goals %}#}
{#<a class="btn btn-default" href="{% url 'dolaposcrumy:editTask' pk=scrumy_goals.pk %}"></a>#}
{#{% endif %}#}

    <tbody>
       {% for scrummer in object_list %}


       <tr>

           <td ><a href="{% url 'dolaposcrumy:add_user' %}"> <span class="glyphicon glyphicon-plus-sign"></span></a> </td>

           <td>{{ scrummer.user_id}} </td>

           <td><a href="{% url 'dolaposcrumy:new_goal' %}"> <span class="glyphicon glyphicon-plus-sign"> </span></a></td>
           <td>
               {% if scrummer.status_id_id == 4 %}
               {{ scrummer.task }}
                   <p>
                       <a class="btn btn-primary btn-sm" href="{% url 'dolaposcrumy:edit_task' scrummer.pk  %}">move</a>
                       <a class="btn btn-danger btn-sm" href="{% url 'dolaposcrumy:delete_goal' scrummer.pk %}">delete</a>
                   </p>

{#                   <a class="btn btn-default" href="{% url 'dolaposcrumy:edit_task' pk= addTask.pk %}">edit</a>#}
               {% endif %}
           </td>
            <td>

               {% if scrummer.status_id_id == 5 %}

               {{ scrummer.task }}
                    <p>
                       <a class="btn btn-primary btn-sm" href="{% url 'dolaposcrumy:edit_task' scrummer.pk  %}">move</a>
                       <a class="btn btn-danger btn-sm" href="{% url 'dolaposcrumy:delete_goal' scrummer.pk %}">delete</a>
                   </p>
               {% endif %}


             </td>
            <td>

               {% if scrummer.status_id_id == 6 %}
               {{ scrummer.task }}
                    <p>
                       <a class="btn btn-primary btn-sm" href="{% url 'dolaposcrumy:edit_task' scrummer.pk  %}">move</a>
                       <a class="btn btn-danger btn-sm" href="{% url 'dolaposcrumy:delete_goal' scrummer.pk %}">delete</a>
                   </p>
           {% endif %}
           </td>
       <td>
               {% if scrummer.status_id_id == 7 %}
               {{ scrummer.task }}
                    <p>
                       <a class="btn btn-primary btn-sm" href="{% url 'dolaposcrumy:edit_task' scrummer.pk  %}">move</a>
                       <a class="btn btn-danger btn-sm" href="{% url 'dolaposcrumy:delete_goal' scrummer.pk %}">delete</a>
                   </p>
           {% endif %}
           </td>
       </tr>
    {% endfor %}

    </tbody>


</table>



{% for scrum in scrumy_goals.scrumygoals_set.all %}
    {{ scrumy_goals }}<br/>
    {{ scrumy_goals.task }}
{% endfor %}

{% endblock %}

dolaposcrumy/templates/dolaposcrumy/new_link.html
{% extends 'dolaposcrumy/base.html' %}
{% block content %}

<h1> ACCESS DENIED <</h1>

{% endblock %}